add_newline = true
scan_timeout = 10

format = "$directory$git_branch$rust[â¯](bold green) "

[rust]
format = "[ğŸ¦€ ](red bold)"

[directory]
truncation_length = 5
truncation_symbol = "../"
truncate_to_repo = false
read_only = " ğŸ”’"

[character]                            
success_symbol = "[âœ](bold green)"

[package]
disabled = true
